### ISSUE TITLE
Using ArcGIS Pro 2.5.0 and Tensor Flow 2.0.0 this no longer works? 

### ISSUE THREAD

**Issue by billharbert** [Esri/raster-deep-learning#25]
Hello, 

After the update to a ArcPro 2.5.0 and an installation of Tensor Flow 2.0.0 in the python image for my work, I am getting this error in both of the tensor flow based Deep Leaerning examples: 

"ERROR Below"
ERROR 002667  Unable to initialize python raster function with scalar arguments. [c:\program files\arcgis\pro\Resources\Raster\Functions\System\DeepLearning\ObjectDetector.py]
Traceback (most recent call last):
  File "c:\program files\arcgis\pro\Resources\Raster\Functions\System\DeepLearning\ObjectDetector.py", line 84, in initialize
    self.child_object_detector.initialize(model, model_as_file)
  File "c:\program files\arcgis\pro\Resources\Raster\Functions\System\DeepLearning\Templates\TemplateBaseDetector.py", line 44, in initialize
    self.load_model(model_path)
  File "c:\program files\arcgis\pro\Resources\Raster\Functions\System\DeepLearning\TensorFlow\ObjectDetectionAPI.py", line 53, in load_model
    od_graph_def = tf.GraphDef()
AttributeError: module 'tensorflow' has no attribute 'GraphDef'

Unable to initialize python raster function with scalar arguments.

"End Error Message"

Can this be fixed?  Any help would be greatly appreciated!  I enjoyed running the examples previously, but neither the Land Classification or Coconut Tree examples seem to work now.

Thanks!

**Comment by billharbert** [comment]
Hello, I received word that these examples would work with TensorFlow 1.14.0.

**Comment by lingtangraster** [comment]
@billharbert Yes, please follow the installation instruction from this documentation for Pro 2.5 deep learning set up: https://pro.arcgis.com/en/pro-app/help/analysis/image-analyst/install-deep-learning-frameworks.htm

**Comment by billharbert** [comment]
Hello and thank you.  I can confirm that these examples work with ArcPro 2.5.0 with Tensorflow 1.14.0 installed.  Thank you very much for your help and quick response.
